#!/data/data/com.termux/files/usr/bin/bash

# Function to set colors
function Coloring {
  NC='\033[0m'
  LRED='\033[1;31m'
  LGREEN='\033[1;32m'
  YELLOW='\033[1;33m'
  PURPLE='\033[1;35m'
  LBLUE='\033[1;36m'
}

# Function to display the banner
banner() {
  toilet "$(figlet "DARK SKIN")" -f term --gay | pv -qL 3000
}

# Clear screen, set colors, and display banner
clear
Coloring
banner
sleep 0.2

# Move darkskin to Termux bin and make it executable
if [ -f "$HOME/DARK_SKIN/darkskin" ]; then
  chmod +x "$HOME/DARK_SKIN/darkskin"
  mv "$HOME/DARK_SKIN/darkskin" "$PREFIX/bin/darkskin"
  chmod +x "$PREFIX/bin/darkskin"
fi

# Function for redirection message
function redirect {
  toilet "   TOOL INSTALL DONE   " -f term -F border --gay | pv -qL 3000

  count=0
  total=3
  start=$(date +%s)
  while [ $count -lt $total ]; do
    sleep 1
    cur=$(date +%s)
    count=$((count + 1))
    pd=$((count * 73 / total))
    runtime=$((cur - start))
    estremain=$(( (runtime * total / count) - runtime ))
    printf "\r%d.%d%% complete - est %d:%0.2d remaining\e[K" $((count * 100 / total)) $(((count * 1000 / total) % 10)) $((estremain / 60)) $((estremain % 60))
  done
  printf "\n"

  # Check if darkskin is successfully moved and run it
  if [ -f "$PREFIX/bin/darkskin" ]; then
    chmod +x setup
    chmod +x darkskin
    chmod +x pakskin
    darkskin
  fi
}

# Checking and installing required packages
toilet " CHECKING INSTALL TOOL " -f term -F border --gay | pv -qL 3000
echo -e "${LGREEN}Checking Required packages${NC}"
packages=("wget" "unzip" "zip" "pv" "figlet" "toilet" "vim" "curl" "rsync" "x11-repo" "qemu-system-i386" "qemu-user-i386")

for pkg in ${packages[@]}; do
  is_pkg_installed=$(dpkg-query -W --showformat='${Status}
' ${pkg} | grep "install ok installed")
  if [ "${is_pkg_installed}" == "install ok installed" ]; then
    echo -e "${LGREEN}${pkg}${NC} is installed."
  else
    echo -e "${LRED}No ${pkg}. Setting up ${pkg}.${NC}"
    pkg install ${pkg} -y
  fi
done

# Call the redirect function
redirect